# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T09:31:31+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity
from fastapi import Header, Path, Query
from pydantic import conint, constr

from models import (
    AccessDeniedException,
    ConflictException,
    CreateAlertManagerDefinitionResponse,
    CreateLoggingConfigurationResponse,
    CreateRuleGroupsNamespaceResponse,
    CreateWorkspaceResponse,
    DescribeAlertManagerDefinitionResponse,
    DescribeLoggingConfigurationResponse,
    DescribeRuleGroupsNamespaceResponse,
    DescribeWorkspaceResponse,
    InternalServerException,
    ListRuleGroupsNamespacesResponse,
    ListTagsForResourceResponse,
    ListWorkspacesResponse,
    PutAlertManagerDefinitionResponse,
    PutRuleGroupsNamespaceResponse,
    ResourceNotFoundException,
    ServiceQuotaExceededException,
    TagKeys,
    TagResourceResponse,
    TagsResourceArnPostRequest,
    ThrottlingException,
    UntagResourceResponse,
    UpdateLoggingConfigurationResponse,
    ValidationException,
    WorkspacesPostRequest,
    WorkspacesWorkspaceIdAlertmanagerDefinitionPostRequest,
    WorkspacesWorkspaceIdAlertmanagerDefinitionPutRequest,
    WorkspacesWorkspaceIdAliasPostRequest,
    WorkspacesWorkspaceIdLoggingPostRequest,
    WorkspacesWorkspaceIdLoggingPutRequest,
    WorkspacesWorkspaceIdRulegroupsnamespacesNamePutRequest,
    WorkspacesWorkspaceIdRulegroupsnamespacesPostRequest,
)

app = MCPProxy(
    contact={
        'email': 'mike.ralphson@gmail.com',
        'name': 'Mike Ralphson',
        'url': 'https://github.com/mermade/aws2openapi',
        'x-twitter': 'PermittedSoc',
    },
    description='Amazon Managed Service for Prometheus',
    license={'name': 'Apache 2.0 License', 'url': 'http://www.apache.org/licenses/'},
    termsOfService='https://aws.amazon.com/service-terms/',
    title='Amazon Prometheus Service',
    version='2020-08-01',
    servers=[
        {
            'description': 'The Amazon Prometheus Service multi-region endpoint',
            'url': 'http://aps.{region}.amazonaws.com',
            'variables': {
                'region': {
                    'default': 'us-east-1',
                    'description': 'The AWS region',
                    'enum': [
                        'us-east-1',
                        'us-east-2',
                        'us-west-1',
                        'us-west-2',
                        'us-gov-west-1',
                        'us-gov-east-1',
                        'ca-central-1',
                        'eu-north-1',
                        'eu-west-1',
                        'eu-west-2',
                        'eu-west-3',
                        'eu-central-1',
                        'eu-south-1',
                        'af-south-1',
                        'ap-northeast-1',
                        'ap-northeast-2',
                        'ap-northeast-3',
                        'ap-southeast-1',
                        'ap-southeast-2',
                        'ap-east-1',
                        'ap-south-1',
                        'sa-east-1',
                        'me-south-1',
                    ],
                }
            },
        },
        {
            'description': 'The Amazon Prometheus Service multi-region endpoint',
            'url': 'https://aps.{region}.amazonaws.com',
            'variables': {
                'region': {
                    'default': 'us-east-1',
                    'description': 'The AWS region',
                    'enum': [
                        'us-east-1',
                        'us-east-2',
                        'us-west-1',
                        'us-west-2',
                        'us-gov-west-1',
                        'us-gov-east-1',
                        'ca-central-1',
                        'eu-north-1',
                        'eu-west-1',
                        'eu-west-2',
                        'eu-west-3',
                        'eu-central-1',
                        'eu-south-1',
                        'af-south-1',
                        'ap-northeast-1',
                        'ap-northeast-2',
                        'ap-northeast-3',
                        'ap-southeast-1',
                        'ap-southeast-2',
                        'ap-east-1',
                        'ap-south-1',
                        'sa-east-1',
                        'me-south-1',
                    ],
                }
            },
        },
        {
            'description': 'The Amazon Prometheus Service endpoint for China (Beijing) and China (Ningxia)',
            'url': 'http://aps.{region}.amazonaws.com.cn',
            'variables': {
                'region': {
                    'default': 'cn-north-1',
                    'description': 'The AWS region',
                    'enum': ['cn-north-1', 'cn-northwest-1'],
                }
            },
        },
        {
            'description': 'The Amazon Prometheus Service endpoint for China (Beijing) and China (Ningxia)',
            'url': 'https://aps.{region}.amazonaws.com.cn',
            'variables': {
                'region': {
                    'default': 'cn-north-1',
                    'description': 'The AWS region',
                    'enum': ['cn-north-1', 'cn-northwest-1'],
                }
            },
        },
    ],
)


@app.get(
    '/tags/{resourceArn}',
    description=""" Lists the tags you have assigned to the resource. """,
    tags=['resource_tag_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def list_tags_for_resource(
    resource_arn: str = Path(..., alias='resourceArn'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/tags/{resourceArn}',
    description=""" Creates tags for the specified resource. """,
    tags=['resource_tag_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def tag_resource(
    resource_arn: str = Path(..., alias='resourceArn'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: TagsResourceArnPostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/tags/{resourceArn}#tagKeys',
    description=""" Deletes tags from the specified resource. """,
    tags=['resource_tag_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def untag_resource(
    resource_arn: str = Path(..., alias='resourceArn'),
    tag_keys: TagKeys = Query(..., alias='tagKeys'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/workspaces',
    description=""" Lists all AMP workspaces, including workspaces being created or deleted. """,
    tags=['resource_tag_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def list_workspaces(
    alias: Optional[constr(min_length=1, max_length=100)] = None,
    max_results: Optional[conint(ge=1, le=1000)] = Query(None, alias='maxResults'),
    next_token: Optional[str] = Query(None, alias='nextToken'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/workspaces',
    description=""" Creates a new AMP workspace. """,
    tags=['workspace_configuration_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def create_workspace(
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: WorkspacesPostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/workspaces/{workspaceId}',
    description=""" Deletes an AMP workspace. """,
    tags=['workspace_configuration_management', 'logging_configuration_handling'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def delete_workspace(
    client_token: Optional[
        constr(pattern=r'[!-~]+', min_length=1, max_length=64)
    ] = Query(None, alias='clientToken'),
    workspace_id: constr(
        pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64
    ) = Path(..., alias='workspaceId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/workspaces/{workspaceId}',
    description=""" Describes an existing AMP workspace. """,
    tags=['workspace_configuration_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def describe_workspace(
    workspace_id: constr(
        pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64
    ) = Path(..., alias='workspaceId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/workspaces/{workspaceId}/alertmanager/definition',
    description=""" Deletes an alert manager definition. """,
    tags=['workspace_configuration_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def delete_alert_manager_definition(
    client_token: Optional[
        constr(pattern=r'[!-~]+', min_length=1, max_length=64)
    ] = Query(None, alias='clientToken'),
    workspace_id: constr(
        pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64
    ) = Path(..., alias='workspaceId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/workspaces/{workspaceId}/alertmanager/definition',
    description=""" Describes an alert manager definition. """,
    tags=['workspace_configuration_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def describe_alert_manager_definition(
    workspace_id: constr(
        pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64
    ) = Path(..., alias='workspaceId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/workspaces/{workspaceId}/alertmanager/definition',
    description=""" Create an alert manager definition. """,
    tags=['workspace_configuration_management', 'alert_manager_definitions_handling'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def create_alert_manager_definition(
    workspace_id: constr(
        pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64
    ) = Path(..., alias='workspaceId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: WorkspacesWorkspaceIdAlertmanagerDefinitionPostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/workspaces/{workspaceId}/alertmanager/definition',
    description=""" Update an alert manager definition. """,
    tags=['workspace_configuration_management', 'alert_manager_definitions_handling'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def put_alert_manager_definition(
    workspace_id: constr(
        pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64
    ) = Path(..., alias='workspaceId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: WorkspacesWorkspaceIdAlertmanagerDefinitionPutRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/workspaces/{workspaceId}/alias',
    description=""" Updates an AMP workspace alias. """,
    tags=['workspace_configuration_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def update_workspace_alias(
    workspace_id: constr(
        pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64
    ) = Path(..., alias='workspaceId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: WorkspacesWorkspaceIdAliasPostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/workspaces/{workspaceId}/logging',
    description=""" Delete logging configuration. """,
    tags=['workspace_configuration_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def delete_logging_configuration(
    client_token: Optional[
        constr(pattern=r'[!-~]+', min_length=1, max_length=64)
    ] = Query(None, alias='clientToken'),
    workspace_id: constr(
        pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64
    ) = Path(..., alias='workspaceId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/workspaces/{workspaceId}/logging',
    description=""" Describes logging configuration. """,
    tags=['workspace_configuration_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def describe_logging_configuration(
    workspace_id: constr(
        pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64
    ) = Path(..., alias='workspaceId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/workspaces/{workspaceId}/logging',
    description=""" Create logging configuration. """,
    tags=['workspace_configuration_management', 'logging_configuration_handling'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def create_logging_configuration(
    workspace_id: constr(
        pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64
    ) = Path(..., alias='workspaceId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: WorkspacesWorkspaceIdLoggingPostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/workspaces/{workspaceId}/logging',
    description=""" Update logging configuration. """,
    tags=['workspace_configuration_management', 'logging_configuration_handling'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def update_logging_configuration(
    workspace_id: constr(
        pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64
    ) = Path(..., alias='workspaceId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: WorkspacesWorkspaceIdLoggingPutRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/workspaces/{workspaceId}/rulegroupsnamespaces',
    description=""" Lists rule groups namespaces. """,
    tags=['workspace_configuration_management', 'alert_manager_definitions_handling'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def list_rule_groups_namespaces(
    max_results: Optional[conint(ge=1, le=1000)] = Query(None, alias='maxResults'),
    name: Optional[
        constr(pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64)
    ] = None,
    next_token: Optional[str] = Query(None, alias='nextToken'),
    workspace_id: constr(
        pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64
    ) = Path(..., alias='workspaceId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/workspaces/{workspaceId}/rulegroupsnamespaces',
    description=""" Create a rule group namespace. """,
    tags=['workspace_configuration_management', 'rule_group_namespace_handling'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def create_rule_groups_namespace(
    workspace_id: constr(
        pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64
    ) = Path(..., alias='workspaceId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: WorkspacesWorkspaceIdRulegroupsnamespacesPostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/workspaces/{workspaceId}/rulegroupsnamespaces/{name}',
    description=""" Delete a rule groups namespace. """,
    tags=['workspace_configuration_management', 'alert_manager_definitions_handling'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def delete_rule_groups_namespace(
    client_token: Optional[
        constr(pattern=r'[!-~]+', min_length=1, max_length=64)
    ] = Query(None, alias='clientToken'),
    name: constr(
        pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64
    ) = ...,
    workspace_id: constr(
        pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64
    ) = Path(..., alias='workspaceId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/workspaces/{workspaceId}/rulegroupsnamespaces/{name}',
    description=""" Describe a rule groups namespace. """,
    tags=['workspace_configuration_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def describe_rule_groups_namespace(
    name: constr(pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64),
    workspace_id: constr(
        pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64
    ) = Path(..., alias='workspaceId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/workspaces/{workspaceId}/rulegroupsnamespaces/{name}',
    description=""" Update a rule groups namespace. """,
    tags=['workspace_configuration_management', 'rule_group_namespace_handling'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def put_rule_groups_namespace(
    name: constr(pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64),
    workspace_id: constr(
        pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64
    ) = Path(..., alias='workspaceId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: WorkspacesWorkspaceIdRulegroupsnamespacesNamePutRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
