# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T09:31:31+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel, conint, constr


class AccessDeniedException(RootModel[Any]):
    root: Any


class AlertManagerDefinitionData(RootModel[str]):
    root: str = Field(..., description='The alert manager definition data.')


class AlertManagerDefinitionStatusCode(Enum):
    CREATING = 'CREATING'
    ACTIVE = 'ACTIVE'
    UPDATING = 'UPDATING'
    DELETING = 'DELETING'
    CREATION_FAILED = 'CREATION_FAILED'
    UPDATE_FAILED = 'UPDATE_FAILED'


class ConflictException(RootModel[Any]):
    root: Any


class DeleteAlertManagerDefinitionRequest(BaseModel):
    pass


class DeleteLoggingConfigurationRequest(BaseModel):
    pass


class DeleteRuleGroupsNamespaceRequest(BaseModel):
    pass


class DeleteWorkspaceRequest(BaseModel):
    pass


class DescribeAlertManagerDefinitionRequest(BaseModel):
    pass


class DescribeLoggingConfigurationRequest(BaseModel):
    pass


class DescribeRuleGroupsNamespaceRequest(BaseModel):
    pass


class DescribeWorkspaceRequest(BaseModel):
    pass


class IdempotencyToken(
    RootModel[constr(pattern=r'[!-~]+', min_length=1, max_length=64)]
):
    root: constr(pattern=r'[!-~]+', min_length=1, max_length=64) = Field(
        ...,
        description='An identifier used to ensure the idempotency of a write request.',
    )


class InternalServerException(RootModel[Any]):
    root: Any


class ListRuleGroupsNamespacesRequest(BaseModel):
    pass


class ListRuleGroupsNamespacesRequestMaxResultsInteger(
    RootModel[conint(ge=1, le=1000)]
):
    root: conint(ge=1, le=1000)


class ListTagsForResourceRequest(BaseModel):
    pass


class ListWorkspacesRequest(BaseModel):
    pass


class ListWorkspacesRequestMaxResultsInteger(RootModel[conint(ge=1, le=1000)]):
    root: conint(ge=1, le=1000)


class LogGroupArn(
    RootModel[
        constr(
            pattern=r'^arn:aws[a-z0-9-]*:logs:[a-z0-9-]+:\d{12}:log-group:[A-Za-z0-9\.\-\_\#/]{1,512}\:\*$'
        )
    ]
):
    root: constr(
        pattern=r'^arn:aws[a-z0-9-]*:logs:[a-z0-9-]+:\d{12}:log-group:[A-Za-z0-9\.\-\_\#/]{1,512}\:\*$'
    )


class LoggingConfigurationStatusCode(Enum):
    CREATING = 'CREATING'
    ACTIVE = 'ACTIVE'
    UPDATING = 'UPDATING'
    DELETING = 'DELETING'
    CREATION_FAILED = 'CREATION_FAILED'
    UPDATE_FAILED = 'UPDATE_FAILED'


class PaginationToken(RootModel[str]):
    root: str = Field(
        ...,
        description='A token used to access the next page in a paginated result set.',
    )


class PutAlertManagerDefinitionRequest(BaseModel):
    clientToken: Optional[IdempotencyToken] = None
    data: AlertManagerDefinitionData


class ResourceNotFoundException(RootModel[Any]):
    root: Any


class RuleGroupsNamespaceArn(RootModel[str]):
    root: str = Field(..., description='An ARN identifying a rule groups namespace.')


class RuleGroupsNamespaceData(RootModel[str]):
    root: str = Field(..., description='The rule groups namespace data.')


class RuleGroupsNamespaceName(
    RootModel[
        constr(pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64)
    ]
):
    root: constr(pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64) = (
        Field(..., description='The namespace name that the rule group belong to.')
    )


class RuleGroupsNamespaceStatusCode(Enum):
    CREATING = 'CREATING'
    ACTIVE = 'ACTIVE'
    UPDATING = 'UPDATING'
    DELETING = 'DELETING'
    CREATION_FAILED = 'CREATION_FAILED'
    UPDATE_FAILED = 'UPDATE_FAILED'


class ServiceQuotaExceededException(RootModel[Any]):
    root: Any


class String(RootModel[str]):
    root: str


class TagKey(
    RootModel[
        constr(pattern=r'^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$', min_length=1, max_length=128)
    ]
):
    root: constr(
        pattern=r'^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$', min_length=1, max_length=128
    )


class TagKeys(RootModel[List[TagKey]]):
    root: List[TagKey]


class TagResourceResponse(BaseModel):
    pass


class TagValue(
    RootModel[
        constr(pattern=r'^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$', min_length=0, max_length=256)
    ]
):
    root: constr(
        pattern=r'^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$', min_length=0, max_length=256
    )


class ThrottlingException(RootModel[Any]):
    root: Any


class Timestamp(RootModel[datetime]):
    root: datetime


class UntagResourceRequest(BaseModel):
    pass


class UntagResourceResponse(BaseModel):
    pass


class UpdateLoggingConfigurationRequest(BaseModel):
    clientToken: Optional[IdempotencyToken] = None
    logGroupArn: LogGroupArn


class Uri(RootModel[constr(min_length=1, max_length=1024)]):
    root: constr(min_length=1, max_length=1024)


class ValidationException(RootModel[Any]):
    root: Any


class WorkspaceAlias(RootModel[constr(min_length=1, max_length=100)]):
    root: constr(min_length=1, max_length=100) = Field(
        ..., description='A user-assigned workspace alias.'
    )


class WorkspaceArn(RootModel[str]):
    root: str = Field(..., description='An ARN identifying a Workspace.')


class WorkspaceId(
    RootModel[
        constr(pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64)
    ]
):
    root: constr(pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64) = (
        Field(..., description='A workspace ID.')
    )


class WorkspaceStatusCode(Enum):
    CREATING = 'CREATING'
    ACTIVE = 'ACTIVE'
    UPDATING = 'UPDATING'
    DELETING = 'DELETING'
    CREATION_FAILED = 'CREATION_FAILED'


class TagsResourceArnPostRequest(BaseModel):
    tags: Dict[str, TagValue] = Field(
        ..., description='The list of tags assigned to the resource.'
    )


class WorkspacesPostRequest(BaseModel):
    alias: Optional[constr(min_length=1, max_length=100)] = Field(
        None, description='A user-assigned workspace alias.'
    )
    clientToken: Optional[constr(pattern=r'[!-~]+', min_length=1, max_length=64)] = (
        Field(
            None,
            description='An identifier used to ensure the idempotency of a write request.',
        )
    )
    tags: Optional[Dict[str, TagValue]] = Field(
        None, description='The list of tags assigned to the resource.'
    )


class WorkspacesWorkspaceIdAlertmanagerDefinitionPostRequest(BaseModel):
    clientToken: Optional[constr(pattern=r'[!-~]+', min_length=1, max_length=64)] = (
        Field(
            None,
            description='An identifier used to ensure the idempotency of a write request.',
        )
    )
    data: str = Field(..., description='The alert manager definition data.')


class WorkspacesWorkspaceIdAlertmanagerDefinitionPutRequest(BaseModel):
    clientToken: Optional[constr(pattern=r'[!-~]+', min_length=1, max_length=64)] = (
        Field(
            None,
            description='An identifier used to ensure the idempotency of a write request.',
        )
    )
    data: str = Field(..., description='The alert manager definition data.')


class WorkspacesWorkspaceIdAliasPostRequest(BaseModel):
    alias: Optional[constr(min_length=1, max_length=100)] = Field(
        None, description='A user-assigned workspace alias.'
    )
    clientToken: Optional[constr(pattern=r'[!-~]+', min_length=1, max_length=64)] = (
        Field(
            None,
            description='An identifier used to ensure the idempotency of a write request.',
        )
    )


class WorkspacesWorkspaceIdLoggingPostRequest(BaseModel):
    clientToken: Optional[constr(pattern=r'[!-~]+', min_length=1, max_length=64)] = (
        Field(
            None,
            description='An identifier used to ensure the idempotency of a write request.',
        )
    )
    logGroupArn: constr(
        pattern=r'^arn:aws[a-z0-9-]*:logs:[a-z0-9-]+:\d{12}:log-group:[A-Za-z0-9\.\-\_\#/]{1,512}\:\*$'
    ) = Field(
        ...,
        description='The ARN of the CW log group to which the vended log data will be published.',
    )


class WorkspacesWorkspaceIdLoggingPutRequest(BaseModel):
    clientToken: Optional[constr(pattern=r'[!-~]+', min_length=1, max_length=64)] = (
        Field(
            None,
            description='An identifier used to ensure the idempotency of a write request.',
        )
    )
    logGroupArn: constr(
        pattern=r'^arn:aws[a-z0-9-]*:logs:[a-z0-9-]+:\d{12}:log-group:[A-Za-z0-9\.\-\_\#/]{1,512}\:\*$'
    ) = Field(
        ...,
        description='The ARN of the CW log group to which the vended log data will be published.',
    )


class WorkspacesWorkspaceIdRulegroupsnamespacesPostRequest(BaseModel):
    clientToken: Optional[constr(pattern=r'[!-~]+', min_length=1, max_length=64)] = (
        Field(
            None,
            description='An identifier used to ensure the idempotency of a write request.',
        )
    )
    data: str = Field(..., description='The rule groups namespace data.')
    name: constr(pattern=r'[0-9A-Za-z][-.0-9A-Z_a-z]*', min_length=1, max_length=64) = (
        Field(..., description='The namespace name that the rule group belong to.')
    )
    tags: Optional[Dict[str, TagValue]] = Field(
        None, description='The list of tags assigned to the resource.'
    )


class WorkspacesWorkspaceIdRulegroupsnamespacesNamePutRequest(BaseModel):
    clientToken: Optional[constr(pattern=r'[!-~]+', min_length=1, max_length=64)] = (
        Field(
            None,
            description='An identifier used to ensure the idempotency of a write request.',
        )
    )
    data: str = Field(..., description='The rule groups namespace data.')


class AlertManagerDefinitionStatus(BaseModel):
    statusCode: AlertManagerDefinitionStatusCode
    statusReason: Optional[String] = None


class CreateAlertManagerDefinitionRequest(BaseModel):
    clientToken: Optional[IdempotencyToken] = None
    data: AlertManagerDefinitionData


class CreateAlertManagerDefinitionResponse(BaseModel):
    status: AlertManagerDefinitionStatus


class CreateLoggingConfigurationRequest(BaseModel):
    clientToken: Optional[IdempotencyToken] = None
    logGroupArn: LogGroupArn


class LoggingConfigurationStatus(BaseModel):
    statusCode: LoggingConfigurationStatusCode
    statusReason: Optional[String] = None


class PutAlertManagerDefinitionResponse(BaseModel):
    status: AlertManagerDefinitionStatus


class PutRuleGroupsNamespaceRequest(BaseModel):
    clientToken: Optional[IdempotencyToken] = None
    data: RuleGroupsNamespaceData


class RuleGroupsNamespaceStatus(BaseModel):
    statusCode: RuleGroupsNamespaceStatusCode
    statusReason: Optional[String] = None


class TagMap(RootModel[Optional[Dict[str, TagValue]]]):
    root: Optional[Dict[str, TagValue]] = None


class TagResourceRequest(BaseModel):
    tags: TagMap


class UpdateLoggingConfigurationResponse(BaseModel):
    status: LoggingConfigurationStatus


class UpdateWorkspaceAliasRequest(BaseModel):
    alias: Optional[WorkspaceAlias] = None
    clientToken: Optional[IdempotencyToken] = None


class WorkspaceStatus(BaseModel):
    statusCode: WorkspaceStatusCode


class WorkspaceSummary(BaseModel):
    alias: Optional[WorkspaceAlias] = None
    arn: WorkspaceArn
    createdAt: Timestamp
    status: WorkspaceStatus
    tags: Optional[TagMap] = None
    workspaceId: WorkspaceId


class WorkspaceSummaryList(RootModel[List[WorkspaceSummary]]):
    root: List[WorkspaceSummary] = Field(
        ..., description='A list of workspace summaries.'
    )


class AlertManagerDefinitionDescription(BaseModel):
    createdAt: Timestamp
    data: AlertManagerDefinitionData
    modifiedAt: Timestamp
    status: AlertManagerDefinitionStatus


class CreateLoggingConfigurationResponse(BaseModel):
    status: LoggingConfigurationStatus


class CreateRuleGroupsNamespaceRequest(BaseModel):
    clientToken: Optional[IdempotencyToken] = None
    data: RuleGroupsNamespaceData
    name: RuleGroupsNamespaceName
    tags: Optional[TagMap] = None


class CreateRuleGroupsNamespaceResponse(BaseModel):
    arn: RuleGroupsNamespaceArn
    name: RuleGroupsNamespaceName
    status: RuleGroupsNamespaceStatus
    tags: Optional[TagMap] = None


class CreateWorkspaceRequest(BaseModel):
    alias: Optional[WorkspaceAlias] = None
    clientToken: Optional[IdempotencyToken] = None
    tags: Optional[TagMap] = None


class CreateWorkspaceResponse(BaseModel):
    arn: WorkspaceArn
    status: WorkspaceStatus
    tags: Optional[TagMap] = None
    workspaceId: WorkspaceId


class DescribeAlertManagerDefinitionResponse(BaseModel):
    alertManagerDefinition: AlertManagerDefinitionDescription


class ListTagsForResourceResponse(BaseModel):
    tags: Optional[TagMap] = None


class ListWorkspacesResponse(BaseModel):
    nextToken: Optional[PaginationToken] = None
    workspaces: WorkspaceSummaryList


class LoggingConfigurationMetadata(BaseModel):
    createdAt: Timestamp
    logGroupArn: LogGroupArn
    modifiedAt: Timestamp
    status: LoggingConfigurationStatus
    workspace: WorkspaceId


class PutRuleGroupsNamespaceResponse(BaseModel):
    arn: RuleGroupsNamespaceArn
    name: RuleGroupsNamespaceName
    status: RuleGroupsNamespaceStatus
    tags: Optional[TagMap] = None


class RuleGroupsNamespaceDescription(BaseModel):
    arn: RuleGroupsNamespaceArn
    createdAt: Timestamp
    data: RuleGroupsNamespaceData
    modifiedAt: Timestamp
    name: RuleGroupsNamespaceName
    status: RuleGroupsNamespaceStatus
    tags: Optional[TagMap] = None


class RuleGroupsNamespaceSummary(BaseModel):
    arn: RuleGroupsNamespaceArn
    createdAt: Timestamp
    modifiedAt: Timestamp
    name: RuleGroupsNamespaceName
    status: RuleGroupsNamespaceStatus
    tags: Optional[TagMap] = None


class RuleGroupsNamespaceSummaryList(RootModel[List[RuleGroupsNamespaceSummary]]):
    root: List[RuleGroupsNamespaceSummary] = Field(
        ..., description='A list of rule groups namespace summary.'
    )


class WorkspaceDescription(BaseModel):
    alias: Optional[WorkspaceAlias] = None
    arn: WorkspaceArn
    createdAt: Timestamp
    prometheusEndpoint: Optional[Uri] = None
    status: WorkspaceStatus
    tags: Optional[TagMap] = None
    workspaceId: WorkspaceId


class DescribeLoggingConfigurationResponse(BaseModel):
    loggingConfiguration: LoggingConfigurationMetadata


class DescribeRuleGroupsNamespaceResponse(BaseModel):
    ruleGroupsNamespace: RuleGroupsNamespaceDescription


class DescribeWorkspaceResponse(BaseModel):
    workspace: WorkspaceDescription


class ListRuleGroupsNamespacesResponse(BaseModel):
    nextToken: Optional[PaginationToken] = None
    ruleGroupsNamespaces: RuleGroupsNamespaceSummaryList
